[package]
name = "cabat_runner"
version = "0.1.0"
edition = "2021"

[features]
debug = []

[dependencies]
cabat_common.path = "../cabat_common" 
cabat_shipyard.path = "../cabat_shipyard" 
glam = "0.29.0"
log.workspace = true
shipyard.workspace = true
winit = "0.30.5"
