[package]
name = "shipyard_renderer"
version = "0.1.0"
edition = "2021"

[features]
default = ["text2d"]
text2d = ["glyphon"]

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
glam = "0.29.0"
glyphon = { git = "https://github.com/grovesNL/glyphon.git", version = "0.6.0", optional = true }
image = "0.25.2"
log = "0.4.22"
pollster = "0.3.0"
shipyard = "0.7"
shipyard_shared = { git = "http://192.168.68.104:3000/BrackenLo/shipyard_shared.git", version = "0.1.0" }
shipyard_tools = { git = "http://192.168.68.104:3000/BrackenLo/shipyard_tools.git", version = "0.1.0" }
wgpu = "22.1.0"
