[package]
name = "cabat_assets"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
cabat_shipyard.path = "../cabat_shipyard"
crossbeam = "0.8.4"
downcast-rs = "1.2.1"
log.workspace = true
parking_lot = "0.12.3"
rustc-hash = "2.0.0"
shipyard.workspace = true
thiserror = "1.0.64"
