[package]
name = "cabat_common"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
raw-window-handle = "0.6.2"
shipyard.workspace = true
cabat_shipyard = { path = "../cabat_shipyard", version = "0.1.0" }
